import 'package:flutter/material.dart';
import 'app_theme_config.dart';

class BuiltInThemes {
  static const oledDark = AppThemeConfig(
    id: 'oled_dark',
    name: 'OLED DARK',
    isBuiltIn: true,
    background: Color(0xFF000000),
    surfaceHigh: Color(0xFF0A0A0A),
    surfaceMid: Color(0xFF050505),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xC0FFFFFF),
    textTertiary: Color(0x78FFFFFF),
    textDisabled: Color(0x4FFFFFFF),
    textMinimal: Color(0x30FFFFFF),
    borderStrong: Color(0x3DFFFFFF),
    borderMedium: Color(0x1AFFFFFF),
    borderSubtle: Color(0x0DFFFFFF),
    accent: Color(0xFFFAFAFA),
    accentEdit: Color(0xFFFF0066),
    accentSuccess: Color(0xFF69F0AE),
    accentDanger: Color(0xFFFF5252),
    logoColor: Color(0xFFFAFAFA),
    accentCascade: Color(0xFF00BCD4),
    accentVibeTransfer: Color(0xFF4CAF50),
    accentRefCharacter: Color(0xFF18FFFF),
    accentRefStyle: Color(0xFFFF00FF),
    accentRefCharStyle: Color(0xFFFFD700),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const softDark = AppThemeConfig(
    id: 'soft_dark',
    name: 'SOFT DARK',
    isBuiltIn: true,
    background: Color(0xFF121212),
    surfaceHigh: Color(0xFF1E1E1E),
    surfaceMid: Color(0xFF181818),
    textPrimary: Color(0xFFE0E0E0),
    textSecondary: Color(0xC0E0E0E0),
    textTertiary: Color(0x78E0E0E0),
    textDisabled: Color(0x4FE0E0E0),
    textMinimal: Color(0x30E0E0E0),
    borderStrong: Color(0x3DE0E0E0),
    borderMedium: Color(0x1AE0E0E0),
    borderSubtle: Color(0x0DE0E0E0),
    accent: Color(0xFFE0E0E0),
    accentEdit: Color(0xFFFF4081),
    accentSuccess: Color(0xFF69F0AE),
    accentDanger: Color(0xFFFF5252),
    logoColor: Color(0xFFE0E0E0),
    accentCascade: Color(0xFF4DD0E1),
    accentVibeTransfer: Color(0xFF66BB6A),
    accentRefCharacter: Color(0xFF40C4FF),
    accentRefStyle: Color(0xFFEA80FC),
    accentRefCharStyle: Color(0xFFFFD740),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const midnight = AppThemeConfig(
    id: 'midnight',
    name: 'MIDNIGHT',
    isBuiltIn: true,
    background: Color(0xFF0A0E1A),
    surfaceHigh: Color(0xFF141929),
    surfaceMid: Color(0xFF0F1322),
    textPrimary: Color(0xFFD0D8F0),
    textSecondary: Color(0xC0D0D8F0),
    textTertiary: Color(0x78D0D8F0),
    textDisabled: Color(0x4FD0D8F0),
    textMinimal: Color(0x30D0D8F0),
    borderStrong: Color(0x3D7B8FCC),
    borderMedium: Color(0x1A7B8FCC),
    borderSubtle: Color(0x0D7B8FCC),
    accent: Color(0xFF7B8FCC),
    accentEdit: Color(0xFFFF0066),
    accentSuccess: Color(0xFF69F0AE),
    accentDanger: Color(0xFFFF5252),
    logoColor: Color(0xFF7B8FCC),
    accentCascade: Color(0xFF4FC3F7),
    accentVibeTransfer: Color(0xFF4CAF50),
    accentRefCharacter: Color(0xFF80D8FF),
    accentRefStyle: Color(0xFFCE93D8),
    accentRefCharStyle: Color(0xFFFFE082),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const pastelPurple = AppThemeConfig(
    id: 'pastel_purple',
    name: 'PASTEL PURPLE',
    isBuiltIn: true,
    background: Color(0xFF1A1424),
    surfaceHigh: Color(0xFF251E32),
    surfaceMid: Color(0xFF201828),
    textPrimary: Color(0xFFE8DCF5),
    textSecondary: Color(0xC0E8DCF5),
    textTertiary: Color(0x78E8DCF5),
    textDisabled: Color(0x4FE8DCF5),
    textMinimal: Color(0x30E8DCF5),
    borderStrong: Color(0x3DB39DDB),
    borderMedium: Color(0x1AB39DDB),
    borderSubtle: Color(0x0DB39DDB),
    accent: Color(0xFFB39DDB),
    accentEdit: Color(0xFFFF69B4),
    accentSuccess: Color(0xFF69F0AE),
    accentDanger: Color(0xFFFF5252),
    logoColor: Color(0xFFB39DDB),
    accentCascade: Color(0xFF80CBC4),
    accentVibeTransfer: Color(0xFFA5D6A7),
    accentRefCharacter: Color(0xFFB2EBF2),
    accentRefStyle: Color(0xFFE1BEE7),
    accentRefCharStyle: Color(0xFFFFE0B2),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const lightPastel = AppThemeConfig(
    id: 'light_pastel',
    name: 'LIGHT PASTEL',
    isBuiltIn: true,
    background: Color(0xFF2A2240),
    surfaceHigh: Color(0xFF352C50),
    surfaceMid: Color(0xFF302748),
    textPrimary: Color(0xFFF2ECFF),
    textSecondary: Color(0xD0F2ECFF),
    textTertiary: Color(0x85F2ECFF),
    textDisabled: Color(0x57F2ECFF),
    textMinimal: Color(0x38F2ECFF),
    borderStrong: Color(0x57CFB8F0),
    borderMedium: Color(0x30CFB8F0),
    borderSubtle: Color(0x1ACFB8F0),
    accent: Color(0xFFCFB8F0),
    accentEdit: Color(0xFFFF80C0),
    accentSuccess: Color(0xFF69F0AE),
    accentDanger: Color(0xFFFF5252),
    logoColor: Color(0xFFCFB8F0),
    accentCascade: Color(0xFF80D8FF),
    accentVibeTransfer: Color(0xFFA5D6A7),
    accentRefCharacter: Color(0xFFB2EBF2),
    accentRefStyle: Color(0xFFE1BEE7),
    accentRefCharStyle: Color(0xFFFFE0B2),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const roseQuartz = AppThemeConfig(
    id: 'rose_quartz',
    name: 'ROSE QUARTZ',
    isBuiltIn: true,
    background: Color(0xFF221620),
    surfaceHigh: Color(0xFF33222C),
    surfaceMid: Color(0xFF2B1C24),
    textPrimary: Color(0xFFF8E2EA),
    textSecondary: Color(0xC0F8E2EA),
    textTertiary: Color(0x78F8E2EA),
    textDisabled: Color(0x4FF8E2EA),
    textMinimal: Color(0x30F8E2EA),
    borderStrong: Color(0x3DD4828F),
    borderMedium: Color(0x1AD4828F),
    borderSubtle: Color(0x0DD4828F),
    accent: Color(0xFFD4828F),
    accentEdit: Color(0xFFFF4081),
    accentSuccess: Color(0xFF69F0AE),
    accentDanger: Color(0xFFFF5252),
    logoColor: Color(0xFFD4828F),
    accentCascade: Color(0xFFE091A0),
    accentVibeTransfer: Color(0xFF81C784),
    accentRefCharacter: Color(0xFF80DEEA),
    accentRefStyle: Color(0xFFF48FB1),
    accentRefCharStyle: Color(0xFFFFCC80),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const emerald = AppThemeConfig(
    id: 'emerald',
    name: 'EMERALD',
    isBuiltIn: true,
    background: Color(0xFF122218),
    surfaceHigh: Color(0xFF1E3328),
    surfaceMid: Color(0xFF182C20),
    textPrimary: Color(0xFFD8F0E0),
    textSecondary: Color(0xC0D8F0E0),
    textTertiary: Color(0x78D8F0E0),
    textDisabled: Color(0x4FD8F0E0),
    textMinimal: Color(0x30D8F0E0),
    borderStrong: Color(0x3D66BB6A),
    borderMedium: Color(0x1A66BB6A),
    borderSubtle: Color(0x0D66BB6A),
    accent: Color(0xFF66BB6A),
    accentEdit: Color(0xFFFF0066),
    accentSuccess: Color(0xFF69F0AE),
    accentDanger: Color(0xFFFF5252),
    logoColor: Color(0xFF66BB6A),
    accentCascade: Color(0xFF69F0AE),
    accentVibeTransfer: Color(0xFF81C784),
    accentRefCharacter: Color(0xFF4DD0E1),
    accentRefStyle: Color(0xFFBA68C8),
    accentRefCharStyle: Color(0xFFFFB74D),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const amberTerminal = AppThemeConfig(
    id: 'amber_terminal',
    name: 'AMBER TERMINAL',
    isBuiltIn: true,
    background: Color(0xFF0A0800),
    surfaceHigh: Color(0xFF1A1408),
    surfaceMid: Color(0xFF110E04),
    textPrimary: Color(0xFFFFBF00),
    textSecondary: Color(0xC0FFBF00),
    textTertiary: Color(0x78FFBF00),
    textDisabled: Color(0x4FFFBF00),
    textMinimal: Color(0x30FFBF00),
    borderStrong: Color(0x3DFFBF00),
    borderMedium: Color(0x1AFFBF00),
    borderSubtle: Color(0x0DFFBF00),
    accent: Color(0xFFFFBF00),
    accentEdit: Color(0xFFFF6600),
    accentSuccess: Color(0xFF76FF03),
    accentDanger: Color(0xFFFF3D00),
    logoColor: Color(0xFFFFBF00),
    accentCascade: Color(0xFFFFD54F),
    accentVibeTransfer: Color(0xFF76FF03),
    accentRefCharacter: Color(0xFFFFE082),
    accentRefStyle: Color(0xFFFF6E40),
    accentRefCharStyle: Color(0xFFFFAB00),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const cyberpunk = AppThemeConfig(
    id: 'cyberpunk',
    name: 'CYBERPUNK',
    isBuiltIn: true,
    background: Color(0xFF0A0014),
    surfaceHigh: Color(0xFF160A24),
    surfaceMid: Color(0xFF100618),
    textPrimary: Color(0xFFE0D0F0),
    textSecondary: Color(0xC0E0D0F0),
    textTertiary: Color(0x78E0D0F0),
    textDisabled: Color(0x4FE0D0F0),
    textMinimal: Color(0x30E0D0F0),
    borderStrong: Color(0x3D00E5FF),
    borderMedium: Color(0x1A00E5FF),
    borderSubtle: Color(0x0D00E5FF),
    accent: Color(0xFF00E5FF),
    accentEdit: Color(0xFFFF0066),
    accentSuccess: Color(0xFF76FF03),
    accentDanger: Color(0xFFFF1744),
    logoColor: Color(0xFF00E5FF),
    accentCascade: Color(0xFF00E5FF),
    accentVibeTransfer: Color(0xFF76FF03),
    accentRefCharacter: Color(0xFF18FFFF),
    accentRefStyle: Color(0xFFFF00FF),
    accentRefCharStyle: Color(0xFFFFD700),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const bazoongafool = AppThemeConfig(
    id: 'bazoongafool',
    name: 'BAZOONGAFOOL',
    isBuiltIn: true,
    background: Color(0xFF16181D),
    surfaceHigh: Color(0xFF1E2128),
    surfaceMid: Color(0xFF1A1D23),
    textPrimary: Color(0xFFD4D8E0),
    textSecondary: Color(0xC0D4D8E0),
    textTertiary: Color(0x78D4D8E0),
    textDisabled: Color(0x4FD4D8E0),
    textMinimal: Color(0x30D4D8E0),
    borderStrong: Color(0x3D5B8DEF),
    borderMedium: Color(0x1A5B8DEF),
    borderSubtle: Color(0x0D5B8DEF),
    accent: Color(0xFF5B8DEF),
    accentEdit: Color(0xFFFF0066),
    accentSuccess: Color(0xFF69F0AE),
    accentDanger: Color(0xFFFF5252),
    logoColor: Color(0xFF5B8DEF),
    accentCascade: Color(0xFF64B5F6),
    accentVibeTransfer: Color(0xFF4CAF50),
    accentRefCharacter: Color(0xFF40C4FF),
    accentRefStyle: Color(0xFFE040FB),
    accentRefCharStyle: Color(0xFFFFD740),
    fontFamily: 'JetBrains Mono',
    fontScale: 1.0,
    brightMode: true,
  );

  static const List<AppThemeConfig> all = [
    oledDark,
    softDark,
    midnight,
    pastelPurple,
    lightPastel,
    roseQuartz,
    emerald,
    amberTerminal,
    cyberpunk,
    bazoongafool,
  ];

  static AppThemeConfig get defaultTheme => oledDark;
}
